language: node_js
before_install:
  - npm install coffee-script
  - npm install mocha
  - npm install chai
node_js:
  - "0.10.3"
  - "0.10"
  - "0.8"
  - "0.6"
notifications:
  irc: "irc.freenode.org#buttercoin-dev"
